config/routes.rb
Rails.application.routes.draw do

  resources :deuces
  devise_for :users
  resources :conversations, only: [:create]
  root 'deuces#index'
  get 'signup' => 'devise/registrations#new'
  post 'signup' => 'devise/registrations#create'
  as :user do
    get 'deuces/index' => 'deuces#index'
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    post 'deuces/join/:id' => 'deuces#join'
    post 'conversations' => 'conversations#create'
    post '/messages/sendMessage' => 'messages#send_message'
    delete 'signout' => 'devise/sessions#destroy'
  end

=begin
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
=end

end

app/models/deuce.rb
class Deuce < ActiveRecord::Base
end

app/controllers/deuces_controller.rb
class DeucesController < ApplicationController
  @@PLAYER_JOINED = "playerJoined"
  @@ROOM_CREATED = "roomCreated"
  @@PRIVATE_CHANNEL = 'privateChannel'
  before_action :set_deuce, only: [:show, :edit, :update, :destroy]

  # GET /deuces
  # GET /deuces.json
  def index
    @deuces = Deuce.where("? < player_count AND player_count < ?", 0, 4)
  end

  def join
    @deuce = Deuce.find(params[:id])

    user_count = 1

    if @deuce[:player2].nil?
      @deuce[:player2] = current_user[:id]
      user_count += 1
    elsif @deuce[:player3].nil?
      @deuce[:player3] = current_user[:id]
      user_count += 1
    elsif @deuce[:player4].nil?
      @deuce[:player4] = current_user[:id]
      user_count += 1
    end

    @deuce[:player_count] = user_count

    respond_to do |format|
      if @deuce.save

        Pusher.trigger("deuce_#{@deuce[:id]}", @@PLAYER_JOINED, {})

        format.html { redirect_to @deuce, notice: 'Successfully joined the game.' }
        format.json { render :Show, status: :ok, location: @deuce }
      else
        render nothing: true
      end
    end
  end
  # GET /deuces/1
  # GET /deuces/1.json
  def show
  end

  # GET /deuces/new
  def new
    @deuce = Deuce.new
  end

  # GET /deuces/1/edit
  def edit
  end

  # POST /deuces
  # POST /deuces.json
  def create
    data = {:name => params[:roomName], :player1 => current_user[:id], :player_count => 1}

    @deuce = Deuce.new(data)

    @deuce.save

    Pusher.trigger(@@PRIVATE_CHANNEL, @@ROOM_CREATED, {})

    redirect_to @deuce
  end

  # PATCH/PUT /deuces/1
  # PATCH/PUT /deuces/1.json
  def update
    respond_to do |format|
      if @deuce.update(deuce_params)
        format.html { redirect_to @deuce, notice: 'Deuce was successfully updated.' }
        format.json { render :show, status: :ok, location: @deuce }
      else
        format.html { render :edit }
        format.json { render json: @deuce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deuces/1
  # DELETE /deuces/1.json
  def destroy
    @deuce.destroy
    respond_to do |format|
      format.html { redirect_to deuces_url, notice: 'Deuce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deuce
      @deuce = Deuce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deuce_params
      params.require(:deuce).permit(:player_count, :name, :player1, :player2, :player3, :player4)
    end
end

app/helpers/deuces_helper.rb
module DeucesHelper
end

app/views/deuces/_form.html.erb
<%= form_for(@deuce) do |f| %>
  <% if @deuce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deuce.errors.count, "error") %> prohibited this deuce from being saved:</h2>

      <ul>
      <% @deuce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_count %><br>
    <%= f.number_field :player_count %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :player1 %><br>
    <%= f.text_field :player1 %>
  </div>
  <div class="field">
    <%= f.label :player2 %><br>
    <%= f.text_field :player2 %>
  </div>
  <div class="field">
    <%= f.label :player3 %><br>
    <%= f.text_field :player3 %>
  </div>
  <div class="field">
    <%= f.label :player4 %><br>
    <%= f.text_field :player4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deuces/edit.html.erb
<h1>Editing Deuce</h1>

<%= render 'form' %>

<%= link_to 'Show', @deuce %> |
<%= link_to 'Back', deuces_path %>

app/views/deuces/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Deuces Card Game</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">
    <script src="/assets/javascripts/deuce.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "conversations"%>
    <%= javascript_include_tag('conversation.js') %>

        <%= javascript_include_tag('deuce.js') %>
        <script>
        var ROOM_CHANNEL = "deuce_";
        var PLAYER_JOINED = "playerJoined";
        var ROOM_CREATED = "roomCreated";
        var pusher
        $(document).ready(function() {
            pusher = new Pusher("a6c97e689cf9fd217899");
            // Subscribe this user to the channel to chat
            var privateChannel = pusher.subscribe(PRIVATE_CHANNEL);
            privateChannel.bind(ROOM_CREATED, function(data) {
                // Refresh div
                $('#gameList').load('/deuces/ #gameList');
            });
        });

        function createGame() {
            var roomName = $('#roomName').val();

            $.ajax({
                url: '/deuces',
                type: 'POST',
                dataType: "json",
                contentType: "application/json",
                data: JSON.stringify(
                    {
                        "roomName": roomName
                    }
                ),
                success: function(data) {
                  console.log("asdsadsaf");
                  window.location = "deuces/"+data["id"];
            pusher.unsubscribe(PRIVATE_CHANNEL);
                    // Subscribe to pusher channel
                    var channel = pusher.subscribe(ROOM_CHANNEL+data["id"]);
                    channel.bind(PLAYER_JOINED, function(eventData) {
                        // Refresh div
                        $('#players').load('/deuces/'+data["id"]+' #players');
                    });
                }
            });
        }

        function joinGame(id) {
            $.ajax({
                url: '/deuces/join/'+id,
                type: 'POST',
                success: function(data) {
                  window.location = "/deuces/"+id;
            pusher.unsubscribe(PRIVATE_CHANNEL);
                    // Subscribe to pusher channel
                    var channel = pusher.subscribe(ROOM_CHANNEL+id);
                    channel.bind(PLAYER_JOINED, function(eventData) {
                        // Refresh div
                        $('#players').load('/deuces/'+id+' #players');
                    });
                }
            });
        }
       </script>

</head>
<body>
    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header" style="padding-top: 50px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="margin: 10px; align-items: center;">
                    <h1 class="tagline" style="align-text: center;">Welcome to an online card game called Deuces</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">
        <hr>

        <div class="row">
            <div class="col-sm-8">
                <h2>How to play</h2>
                <p>The game is named Deuces after the fact that twos are the largest valued cards in the game.  The deck is split evenly between each player.  The order of the suit card from lowest to highest is diamond, clover, heart, then spades.  The player with lowest value 3 of diamonds must go first.  Their first move must incorporate the 3 of diamonds.  The current player in power can play a single, double, triple, quadruples, or any 5 combination card (which are the same as a poker hand. For information about poker hands <a href="https://en.wikipedia.org/wiki/List_of_poker_hands">click here</a>).  Everyone else following that player must play the same type of combo.</p>
                <p>For example, if a player plays a straight then the following players must play a 5 combo that is higher than the pervious player until no one can beat the last played cards.  Then the player that played the highest cards that no one can beat has the power.  Repeat until one player gets rid of their hand.</p>
                <p>
                    <input type="text" placeholder="Room Name..." id="roomName"/>
                    <button class="btn btn-primary btn-lg" onclick="createGame()">Start New Game &raquo;</button>
                </p>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        <div id="gameList" class="row">
            <div class="container-fluid">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Lobby Name</th>
                                <th>Player One</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                          <% unless @deuces.nil? %>
                           <% @deuces.each do |deuce| %>
                           <% user = User.find(deuce[:player1]) %>
                           <tr>
                               <td><%= deuce[:name] %></td>
                               <td><%= user.nil? ? "Annonymous" : user[:name] %></td>
                               <td><button class="btn btn-primary btn-lg" onclick="joinGame(<%= deuce[:id] %>)">Join</button></td>
                           </tr>
                           <% end %>
                       <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <hr>

    </div>

</body>

</html>

app/views/deuces/new.html.erb
<h1>New Deuce</h1>

<%= render 'form' %>

<%= link_to 'Back', deuces_path %>

app/views/deuces/show.html.erb
<div style="padding-top: 50px; width:99%; height: 99%;">
<p id="notice"><%= notice %></p>
  <center><h1><%= @deuce[:name] %></h1></center>
  <hr/>
  <center><button class="btn btn-primary btn-lg">Start Game</button></center>
<div class="content-box">
  <center>
  <div class="players">
    <div class="player-center-top" style="margin: 10px; height: 150px; width 150px;">
    <% user = User.find(@deuce[:player1]) %>
       <center><h2><%= user[:name] %></h2></center>
       <%= image_tag("special.jpg", class: "img-circle img-responsive img-center", size: "100x100") %>
    </div>

    <div class="player-left" style="margin: 10px;">
    <% if ! @deuce[:player2].nil? %>
      <% user = User.find(@deuce[:player2]) %>
      <center><h2><%= user[:name] %></h2></center>
      <%= image_tag("creep.png", class: "img-circle img-responsive img-center", size: "100x100") %>
    <% end %>
    </div>

    <div class="player-right" style="margin: 10px;">
    <% if ! @deuce[:player3].nil? %>
      <% user = User.find(@deuce[:player3]) %>
      <center><h2><%= user[:name] %></h2></center>
      <%= image_tag("joy.jpeg", class: "img-circle img-responsive img-center", size: "100x100") %>
    <% end %>
    </div>
    <div class="player-center-bottom col-md-2" style="margin: 10px;">
    <% if ! @deuce[:player4].nil? %>
      <% user = User.find(@deuce[:player4]) %>
      <center><h2><%= user[:name] %></h2></center>
      <%= image_tag("troll.png", class: "img-circle img-responsive img-center", size: "100x100") %>
    <% end %>
  </div>
  </div>
</center>
</div>
</div>


<div id="chatbox">
  <div class="chatboxTitle">
    Game Chat
  </div>
  <div class="chatContainer">
  <div id="messagesArea"></div>
  <hr/>
  <center>
  <div id="messageInputBoxWrapper">
    <input type="text" class="form-control" id="messageInputBox" placeholder="Message ..."/>
  </div>
  <button type="button" class="btn btn-success btn-sm" onclick="sendMessage(<%= current_user[:id] %>)">Send</button>
</center>
</div>
</div>