config/routes.rb
Rails.application.routes.draw do

  resources :deuces
  devise_for :users
  resources :conversations, only: [:create]
  root 'deuces#index'
  get 'signup' => 'devise/registrations#new'
  post 'signup' => 'devise/registrations#create'
  as :user do
    get 'deuces/index' => 'deuces#index'
    get 'signin' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    post 'deuces/join/:id' => 'deuces#join'
    post 'conversations' => 'conversations#create'
    post '/messages/sendMessage' => 'messages#send_message'
    delete 'signout' => 'devise/sessions#destroy'
  end

=begin
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
=end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :conversations, :foreign_key => :sender_id
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  def new
    super
  end

   #POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  private
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user).order("created_at DESC")
  end

  def show
    @users = User.find(params[:id])
  end

  def new
    @users = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render action: "new"
    end
  end

  def update
    @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
  <!-- Not implemented on tutorial -->
  <div class="col-md-4 pull-left" >
    <div style="height: 300px; overflow-y: auto;">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Users In Game</div>

        <!-- Table -->
        <table class="table" style="align-items: pull-left">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each_with_index do |user, index| %>
              <tr>
                <td><%= index +=1 %></td>
                <td><%= user.name %></td>
                <td>
                  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_user.id, "data-rip" => user.id %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div style="height: 400px; overflow-y: auto;" class="col-md-6 pull-right">
        <h3>Your Conversations</h3>
      <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("http://placehold.it/50x50", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>
    </div>

  </div>

  <div class="col-md-4">

  </div>

</div>